version: "3.8"

services:
    zookeeper:
        image: bitnami/zookeeper
        networks:
            - app
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: bitnami/kafka
        networks:
            - app
        ports:
            - "9092:9092"
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: "yes"
    system:
        image: system:1.0-SNAPSHOT
        networks:
            - app
        deploy:
            replicas: 3
        depends_on: 
            - kafka
            - zookeeper
        environment:
            MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_SERVER}"
    inventory:
        image: inventory:1.0-SNAPSHOT
        networks:
            - app
        depends_on: 
            - kafka
            - zookeeper
        environment:
            MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_SERVER}"
    query:
        image: query:1.0-SNAPSHOT
        networks:
            - app
        depends_on: 
            - kafka
            - zookeeper
        ports:
            - "9080:9080"
        environment:
            InventoryClient_mp_rest_url: http://inventory:9085
            MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_SERVER}"
networks:
    app:
        name: ${NETWORK}
