# This workflow will test the guide application.
# For more information about building and testing Java,
# see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test application

on:
  pull_request:
    branches: [ qa ]
    
jobs:
  java8build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finish

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: unset _JAVA_OPTIONS
    - name: Run tests
      run: sudo ../scripts/testApp.sh
    - name: Post tests
      if: always()
      run: docker images
